version: '3.8'

services:
  traefik:
    image: traefik:v2.10.3
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    environment:
      TZ: Asia/Tokyo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../config/traefik/dev-traefik.toml:/etc/traefik/traefik.toml:ro
    labels:
      traefik.enable: true
      traefik.http.routers.dashboard.entrypoints: web
      traefik.http.routers.dashboard.service: api@internal
    networks:
      - traefik-network
  whoami:
    image: traefik/whoami:v1.9
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.entrypoints: web
    networks:
      - traefik-network

networks:
  traefik-network: