version: '3.8'

services:
  nginx:
    image: nginx:1.25.1-alpine
    ports:
      - 80:80
      - 4010:80
    volumes:
      - ../../config/nginx/dev-server.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server

  server:
    build:
      context: ../..
      dockerfile: dockerfiles/dev/server.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../../server:/github.com/oribe1115/server/speQ
    command: air -c /github.com/oribe1115/server/speQ/.air.toml
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOSTNAME: mariadb
      DB_PORT: 3306
      DB_DATABASE: speq
      ROOT_USER: traP

  mariadb:
    image: mariadb:10.7.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: speq
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - "../../schema/db/schema.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD
      interval: 1s
      timeout: 10s
      retries: 60

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - 9090:9090
    volumes:
      - ../../config/prometheus/dev-prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana-enterprise:10.0.1
    ports:
      - 3001:3000
    volumes:
      - ../../dev-data/grafana/grafana_data:/var/lib/grafana