version: '3.8'

services:
  traefik:
    image: traefik:v2.10.3
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    environment:
      TZ: Asia/Tokyo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

