name: Server

on:
  push:
    branches:
      - 'main'
    paths:
      - server/**/*
      - .github/workflows/server.yaml
  pull_request:
    paths:
      - server/**/*
      - .github/workflows/server.yaml

jobs:
  format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Format
        run: go fmt ./...
        working-directory: ./server/
  
  build:
    name: Check build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build
        run: go build .
        working-directory: ./server/
  